name: Phaser Deploy

on:
  push:
    branches:
      - 'main'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Short Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME#main/}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "./"
          EXCLUDE: "/.git/, /.github/"
          TARGET: "/opt/1panel/www/sites/games/index/${{ env.BRANCH_NAME }}"
          ARGS: "-avz --delete"
